name: PDF转Markdown

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  convert-pdf:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 安装依赖
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      # 使用正确镜像名称和标签
      - name: PDF转HTML
        uses: docker://mnuessler/pdf2htmlex:latest
        with:
          args: pdf/Myresearch_01.pdf output.html

      - name: HTML转MD
        uses: docker://pandoc/core:3.1
        with:
          args: --output=output.md output.html

      - name: 上传结果
        uses: actions/upload-artifact@v4
        with:
          name: markdown-output
          path: output.md
