name: PDF转Markdown

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  convert-pdf:
    runs-on: ubuntu-22.04
    steps:
      # 步骤1：检出仓库代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 步骤2：安装基础依赖（仅需poppler-utils）
      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      # 步骤3：使用Docker镜像转换PDF到HTML（跳过本地安装）
      - name: PDF转HTML
        uses: docker://bwasti/pdf2htmlex:latest
        with:
          args: pdf/Myresearch_01.pdf output.html  # 输入输出路径

      # 步骤4：HTML转Markdown
      - name: HTML转MD
        uses: docker://pandoc/core:3.5
        with:
          args: >-
            --output=output.md
            output.html

      # 步骤5：上传结果
      - name: 上传结果
        uses: actions/upload-artifact@v4
        with:
          name: markdown-output
          path: output.md
