name: Sync English Data
on:
  schedule:
    - cron: '0 * * * *'  # 每小时同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:  # 新增权限配置
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 确保获取完整历史记录

    - name: Download Data
      run: |
        # 使用全大写的用户名
        curl -s -o data/english-data.json \
        "https://raw.githubusercontent.com/SU-COF-HR/Su-cof-HR.github.io/main/data/english-data.json"

    - name: Commit and Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/english-data.json
        
        # 仅在数据变化时提交
        if git diff --quiet --exit-code; then
          echo "没有变化需要提交"
        else
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        fi
